### ISSUE TITLE
Immediately after installing NameMC+ my skin on NameMC is white.

### ISSUE THREAD

**Issue by geo3p** [M6yo/NameMCplus#12] opened 2021-09-06 23:43 UTC
I downloaded and installed the extension, opened a new tab of NameMC, and searched up my name. To my surprise the skin turned completely white and didn't have the right layers. Video below will be self explanatory.
Video: https://gyazo.com/97e1d8866ff6f4227e17bfcd3e885ea1
Browser: Brave
Device: Windows 10

Edit: After re-watching the video It also doesn't show the cape I have equipped equipped on my skin/profile.

**Comment by emmsixx** [comment] 2021-09-06 23:51
I can confirm that I can reproduce this issue on my machine. I am also using Brave on Windows 10. 

The only thing that sets your skin apart is that you seem to have a white background and the skinviewer mistakes that for being part of the skin. A temporary solution to this would be to simply edit your skin to fix this issue. If you need any help with this I could probably photoshop together an edited version for you.

Furthermore, NameMC itself can not properly handle your skin's jacket layer so it completely turns it off. 

Hopefully this helps, I will keep this issue open in case @ItsOrius or @withdrew want to add anything. We will however look into this and see if we can find a way to prevent this in the future.

P.S. As for your cape, I released a fix a few hours ago since @withdrew committed broken code to main. You will need to hover over it to see it render. We might make changes to this so a cape will render automatically upon opening the page, but I can not guarantee that at the moment.

Edit: mcuserna.me also seems to render it with the white layer on top. Possibly a skinview3d issue

**Comment by bribes** [comment] 2021-09-06 23:53
It is a skinview3d issue.

**Comment by geo3p** [comment] 2021-09-07 00:07
Hey, thanks for reviewing my submission, just wanted to thank you for offering but I will edit my skin and fix the jacket layer. The skin is just a complete meme so the only thing that was wrong to my knowledge was the white layer. 

Thank you again and have a great day.
-geo3p

**Comment by drainer** [comment] 2021-09-07 00:08
As a mcuserna.me developer I can confirm this is a skinview3d issue. Skins will need to be altered to fix this. I will look into adding onto 88/skinview3d-patches to perhaps include a permanent fix to this. Thanks for reporting :)

**Closed as completed** 2021-09-07 00:11 UTC
